import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.vision': 'The Vision',
    'nav.residences': 'Residences',
    'nav.floorplan': 'Floor Plan',
    'nav.builder': 'Builder Spec',
    'nav.location': 'Location',
    'nav.contact': 'Contact',
    'nav.leadCenter': 'Investor Lead Center',

    // Hero
    'hero.badge': 'A Signature Residential Landmark in Uttara, Dhaka',
    'hero.title.part1': 'Architectural Purity.',
    'hero.title.part2': 'Infinite Daylight.',
    'hero.title.part3': 'Crafted For Generations.',
    'hero.subtitle': 'A unique collection of 36 boutique residence units in Dakshinkhan, Uttara. Fully-detached on three sides, centering bespoke materials and rigorous structural safety.',
    'hero.cta.discover': 'Explore Catalog',
    'hero.cta.contact': 'Bespoke Inquiries',
    'hero.spec.units': '36 Corner Unts',
    'hero.spec.stories': '10-Storied Building',
    'hero.spec.daylight': '100% Core Daylight',
    'hero.spec.privacy': 'Triple-Side Detached',

    // Vision
    'vision.badge': 'PHILOSOPHY & CRAFTSMANSHIP',
    'vision.title': 'Quiet Luxury. Structurally Refined.',
    'vision.subtitle': 'Every detail of Abrar Tower-2 has been sculpted to project status, durability, and a genuine residential respite that outlasts generations.',
    'vision.card1.title': 'Three-Side Open Purity',
    'vision.card1.desc': 'Engineered with massive setback clearances, allowing absolute wind alignment and natural illumination across every private corner.',
    'vision.card2.title': 'BSRM Extreme Reinforcement',
    'vision.card2.desc': 'Constructed exclusively with certified BSRM 72.5 grade steel, delivering critical seismic-resistance levels.',
    'vision.card3.title': 'Aesthetic Compact Forms',
    'vision.card3.desc': 'Pairing tactile concrete textures with gold accents and high-durability floor lobbies that radiate a boutique lifestyle.',
    'vision.stat.stories': 'Stories of Purity',
    'vision.stat.seismic': 'Seismic Stability',
    'vision.stat.lobbies': 'Lobby Portals',

    // Residences
    'residences.badge': 'THE RESIDENCES OVERVIEW',
    'residences.title': 'Select Your Layout Matrix',
    'residences.subtitle': 'Two high-efficiency variants spanning floors 1 through 9. Carefully proportioned with expansive balconies, cross-ventilated bedroom blocks, and independent staff suites.',
    'residences.tab.front': 'Front Layer (Flat A & B)',
    'residences.tab.rear': 'Rear Layer (Flat C & D)',
    'residences.specs.title': 'Standard Layout Metrics',
    'residences.specs.area': 'Gross Floor Area',
    'residences.specs.beds': 'Bedrooms',
    'residences.specs.baths': 'Bathrooms',
    'residences.specs.balconies': 'Semi-enclosed Balconies',
    'residences.specs.lift': 'Direct Core Elevators',
    'residences.specs.status': 'Availability Gating',
    'residences.specs.status.available': 'Active Allocation',
    'residences.specs.status.sold': 'Fully Transacted',
    'residences.specs.price': 'Allocation Premium',
    'residences.cta.reserve': 'Request Unit Reservation',
    'residences.cta.schedule': 'Schedule Site Inspection',

    // FloorPlan Tool interface
    'floorplan.badge': 'INTERACTIVE BIM SIMULATION',
    'floorplan.title': 'Volumetric Structural Inspector',
    'floorplan.subtitle': 'Explore our live 3D engineering twin. Use the controls below to dissect concrete slabs, simulate solar pathways, perform wall diagnostics, and trigger real-time dimensions.',
    'floorplan.ctrl.layer': 'Structural Slab Target',
    'floorplan.ctrl.all': 'Full 3D Tower',
    'floorplan.ctrl.roof': 'Rooftop Community',
    'floorplan.ctrl.panoramic': 'Panoramic (Floors 7-9)',
    'floorplan.ctrl.executive': 'Executive (Floors 4-6)',
    'floorplan.ctrl.ground': 'Ground Lobby & Car Stalls',
    'floorplan.ctrl.renderMode': 'Render Toggle Mode',
    'floorplan.ctrl.render.solid': 'Layered Solid',
    'floorplan.ctrl.render.blue': 'Blueprint Glass',
    'floorplan.ctrl.light': 'Lighting & Solar Simulation',
    'floorplan.ctrl.light.noon': 'Noon Sun',
    'floorplan.ctrl.light.morning': 'Morning Sun',
    'floorplan.ctrl.light.dusk': 'Dusk Ambient',
    'floorplan.ctrl.light.midnight': 'Midnight Glow',
    'floorplan.ctrl.measure': 'Measure Distance',
    'floorplan.ctrl.clear': 'Clear Points',
    'floorplan.ctrl.elevations': 'Standard Elevations',
    'floorplan.ctrl.elev.north': 'North Elev',
    'floorplan.ctrl.elev.south': 'South Iso',
    'floorplan.ctrl.elev.top': 'Rooftop Top',
    'floorplan.ctrl.orbit': 'Orbit Dynamics',
    'floorplan.ctrl.zoom': 'ZOOM SPEED',
    'floorplan.ctrl.pan': 'PAN DYNAMICS',
    'floorplan.ctrl.vr': 'Toggle VR Stereo View',
    'floorplan.ctrl.vr.active': 'VR Mode: Stereo (Active)',
    'floorplan.ctrl.capture': 'Capture Site Inspection',
    'floorplan.ctrl.capture.title': 'Abrar-2 Field Inspection Camera',
    'floorplan.ctrl.capture.shutter': 'Trigger Capture Frame',
    'floorplan.ctrl.capture.toggleSource': 'Toggle Source (Webcam/3D)',
    'floorplan.ctrl.capture.cancel': 'Cancel Audit',
    'floorplan.ctrl.capture.save': 'Save Inspection JPEG',
    'floorplan.ctrl.hud.hide': 'Hide HUD Overlay',
    'floorplan.ctrl.hud.show': 'HUD Hidden',
    'floorplan.ctrl.tower.isolate': 'Isolate Flat A/B',
    'floorplan.ctrl.tower.composite': 'Show Complete Tower',
    'floorplan.ctrl.pure': 'Pure Cinematic View',

    // BuilderConsole
    'builder.badge': 'B2B DEVELOPER HUB & JOINT VENTURES',
    'builder.title': 'Builder Specs & Land JVs',
    'builder.subtitle': 'An engineering-first portal designed for institutional investors, land-owners, and structural engineering firms to evaluate development codes, calculate site allocation, and audit materials registers.',
    'builder.tab.far': 'RAJUK FAR JV Calculator',
    'builder.tab.specs': 'B2B Engineering Spec Register',
    'builder.tab.cad': 'Developer CAD & Test Packages',
    'builder.calc.parameters': 'Estimate Share Ratio',
    'builder.calc.parameters.desc': 'Drag variables below to model gross building layouts and landowner allocations depending on road widths.',
    'builder.calc.plot': 'PLOT SIZE',
    'builder.calc.road': 'ACCESS ROAD WIDTH',
    'builder.calc.mgc': 'MAX GROUND COVERAGE (MGC)',
    'builder.calc.ownerShare': 'LAND OWNER SHARE',
    'builder.calc.warning': 'FAR values correspond directly to Section 18 of the RAJUK Dhaka Building Code 2008. Road width measurements represent clear right-of-ways verified under the current municipal map.',
    'builder.forecasts': 'MUNICIPAL DEVELOPMENT FORECASTS',
    'builder.forecasts.far': 'RAJUK FAR Ratio',
    'builder.forecasts.multiplier': 'Allowable Multiplier',
    'builder.forecasts.gross': 'Gross Build Area',
    'builder.forecasts.circulation': 'Including Circulation',
    'builder.forecasts.stories': 'Estimated Storeys',
    'builder.forecasts.mgccompliant': 'MGC compliant height',
    'builder.forecasts.shareDist': 'Est. Share Distribution (Based on ~900 sqft average unit sizes)',
    'builder.forecasts.landowner': 'Land Owner',
    'builder.forecasts.devshare': 'Developer Share',
    'builder.forecasts.ownerAppor': 'LAND OWNER APPORTIONMENT',
    'builder.forecasts.devAppor': 'DEVELOPER COMPANY APPORTIONMENT',
    'builder.forecasts.apartments': 'Standard Apartments',
    'builder.forecasts.shares': 'Commercial Shares',
    'builder.forecasts.shareArea': 'SHARE AREA',
    'builder.forecasts.note': '*Calculating estimate only. Our board structures tailored joint venture alignments accommodating advance signature premiums.',
    'builder.forecasts.propose': 'Propose Land JV',
    'builder.specs.title': 'Engineering Quality Matrix',
    'builder.specs.desc': 'Comparing municipal minimum benchmarks to Abrar\'s signature build levels.',
    'builder.specs.qa': 'QA/QC CERTIFIED LOGS',
    'builder.specs.sector': 'STRUCTURAL SECTOR',
    'builder.specs.dhakaMin': 'STANDARD DHAKA MINIMUM',
    'builder.specs.abrarExcel': 'ABRAR TOWER-2 EXCELLENCE TIER',
    'builder.specs.margin': 'MUNICIPAL MARGIN',
    'builder.cad.title': 'Request DXF / PDF Blueprints',
    'builder.cad.desc': 'Architects, developers, and municipal planners can request instant extraction of structural floor layouts, piling logs, and certified RAJUK layouts.',
    'builder.cad.company': 'COMPANY / DEVELOPER FIRM',
    'builder.cad.email': 'CORPORATE EMAIL ADDRESS',
    'builder.cad.designation': 'DESIGNATION / REPRESENTATION',
    'builder.cad.submit': 'Generate CAD Package',
    'builder.cad.ready': 'Ready',
    'builder.cad.dataset': 'CURRENT DATASET INDEX',
    'builder.cad.note': 'Accessing standard records requires corporate registration. For immediate structural queries, please contact Mohammed Abdul Momen directly.',

    // Location
    'location.badge': 'PHYSICAL ADDRESS & BESPOKE GEOGRAPHY',
    'location.title': 'Dakshinkhan Purity Core',
    'location.subtitle': 'Positioned in Sector-01 adjacent East Faydabad, Dakshinkhan. High, water-logging-safe geographic profile inside the planned expansion limits of Uttara.',
    'location.directions': 'Secure Dynamic Commute Router',
    'location.directions.desc': 'Evaluate exact vehicle commute durations and street pathway profiles from Dhaka core points directly to the piling site.',
    'location.direction.source': 'Select Transit Starting Anchor',
    'location.direction.source.airport': 'Hazrat Shahjalal International Airport (1.8 km)',
    'location.direction.source.station': 'Uttara North Metro Rail Station (3.2 km)',
    'location.direction.source.highway': 'Dhaka-Mymensingh Highway (1.2 km)',
    'location.direction.routeInfo': 'Verified Route Diagnostics',
    'location.direction.time': 'Commute Period',
    'location.direction.infrastructure': 'Pathway Profile',
    'location.direction.landmarks': 'Commute Anchor Points',
    'location.pin': 'Bespoke Cartography Coordinate',

    // Contact form panel
    'contact.badge': 'TRANSACTIONS & ALLOCATION DETAILS',
    'contact.title': 'Secure Your Allocation Premium',
    'contact.subtitle': 'Our board structures direct corporate agreements and escrow-backed cash schedules. Register structural intent or schedule an onsite technical inspection.',
    'contact.form.title': 'Structural Registry & Escrow Request',
    'contact.form.name': 'Your Corporate / Full Name',
    'contact.form.email': 'Corporate / Secured Email Address',
    'contact.form.phone': 'Authorized Mobile / Contact Channel',
    'contact.form.flat': 'Bespoke Floor & Flat Unit Coordinates',
    'contact.form.flat.select': 'Select Desired Blueprint Grid',
    'contact.form.flat.opt': 'Grid Unit',
    'contact.form.flat.suite': 'Bespoke Duplex Core Suite (Request Quote)',
    'contact.form.intent': 'Inquiry Designation & Intent Protocol',
    'contact.form.intent.select': 'Select Registry Phase',
    'contact.form.intent.investor': 'JV Investor Proposal (Equity Allocation)',
    'contact.form.intent.buyer': 'Private Corner Apartment Reservation',
    'contact.form.intent.architect': 'Structural Blueprint & Geolog Audit',
    'contact.form.notes': 'Registry Supplemental Notes / Specialized Requests',
    'contact.form.submit': 'Transmit Secure Intent',
    'contact.form.security': 'Secure ISO-27001 TLS Handshake Active',
    'contact.escrow': 'Verified Corporate Escrow Details',
    'contact.escrow.desc': 'Secure registration is handled directly through our designated financial partners. Escrow deposits ensure priority lot reservations.',
    'contact.escrow.beneficiary': 'BENEFICIARY ACCOUNT',
    'contact.escrow.institution': 'CLEARING INSTITUTION',
    'contact.escrow.routing': 'ROUTING TRANSIT SWIFT',
    'contact.escrow.address': 'OFFICIAL ESCROW HQ',

    // Chatbot
    'chatbot.title': 'Abrar-2 Private Architectural AI',
    'chatbot.status': 'B2B Compliance Core Online',
    'chatbot.placeholder': 'Ask about FAR rules, BSRM Grade, pile depths...',
    'chatbot.suggest.far': 'What is the RAJUK FAR score for 10 Katha?',
    'chatbot.suggest.seismic': 'What seismic parameters were engineered?',
    'chatbot.suggest.materials': 'Tell me about the concrete and steel grades.'
  },
  bn: {
    // Header
    'nav.home': 'হোম',
    'nav.vision': 'আমাদের দর্শন',
    'nav.residences': 'রেসিডেন্স',
    'nav.floorplan': 'ফ্লোর প্ল্যান',
    'nav.builder': 'বিল্ডার স্পেক',
    'nav.location': 'অবস্থান',
    'nav.contact': 'যোগাযোগ',
    'nav.leadCenter': 'ইনভেস্টর লিড সেন্টার',

    // Hero
    'hero.badge': 'উত্তরা, ঢাকায় একটি অভূতপূর্ব আবাসিক ল্যান্ডমার্ক',
    'hero.title.part1': 'স্থাপত্যের বিশুদ্ধতা।',
    'hero.title.part2': 'অফুরন্ত আলো।',
    'hero.title.part3': 'প্রজন্মের জন্য নির্মিত।',
    'hero.subtitle': 'দক্ষিণখান, উত্তরায় ৩৬টি অনন্য বুটিক অ্যাপার্টমেন্টের এক দৃষ্টিনন্দন সংগ্রহ। তিন দিকে সম্পূর্ণ খোলা, উন্নত কাঁচামাল এবং সর্বোচ্চ কাঠামোগত নিরাপত্তার সমন্বয়।',
    'hero.cta.discover': 'ক্যাটালগ দেখুন',
    'hero.cta.contact': 'সরাসরি অনুসন্ধান',
    'hero.spec.units': '৩৬টি কর্নার ইউনিট',
    'hero.spec.stories': '১০-তলা বিশিষ্ট ভবন',
    'hero.spec.daylight': '১০০% পর্যাপ্ত আলো',
    'hero.spec.privacy': 'তিন দিকে সম্পূর্ণ খোলা',

    // Vision
    'vision.badge': 'দর্শন এবং নির্মাণশৈলী',
    'vision.title': 'অভিজাত আভিজাত্য। কাঠামোগত উৎকর্ষ।',
    'vision.subtitle': 'আবরার টাওয়ার-২ এর প্রতিটি কোণ এমনভাবে ডিজাইন করা হয়েছে যা আপনার মর্যাদা ও আভিজাত্যকে প্রজন্ম থেকে প্রজন্মে বহন করে নিয়ে যাবে।',
    'vision.card1.title': 'তিন দিকে সম্পূর্ণ খোলা',
    'vision.card1.desc': 'বিশাল ফাঁকা জায়গা রেখে নির্মিত, যার ফলে প্রতিটি অ্যাপার্টমেন্টে মনোরম বাতাস এবং পর্যাপ্ত দিনের আলো খেলা করবে।',
    'vision.card2.title': 'বিএসআরএম এক্সট্রিম রিইনফোর্সমেন্ট',
    'vision.card2.desc': 'সম্পূর্ণ প্রত্যয়িত বিএসআরএম ৭২.৫ গ্রেড স্টিলের মাধ্যমে নির্মিত, যা সর্বোচ্চ মাত্রার ভূমিকম্প নিরোধক নিরাপত্তা প্রদান করে।',
    'vision.card3.title': 'দৃষ্টিনন্দন কমপ্যাক্ট ডিজাইন',
    'vision.card3.desc': 'কংক্রিট টেক্সচার, সোনালী রঙের কারুকাজ এবং অতি টেকসই লবির সমন্বয়ে একটি বিলাসবহুল জীবনযাত্রার নিশ্চয়তা।',
    'vision.stat.stories': 'বিশুদ্ধ তলাসমূহ',
    'vision.stat.seismic': 'ভূমিকম্পে স্থায়িত্ব',
    'vision.stat.lobbies': 'প্রবেশ লবিগুলো',

    // Residences
    'residences.badge': 'আবাসন ওভারভিউ',
    'residences.title': 'আপনার ফ্লোর প্ল্যান নির্বাচন করুন',
    'residences.subtitle': '১ থেকে ৯ তলা বিশিষ্ট অত্যন্ত চমৎকার দুটি সংস্করণ। খোলামেলা বারান্দা, চমৎকার ভেন্টিলেশন ও নিজস্ব স্টাফ কোয়ার্টারের আধুনিক সুব্যবস্থা।',
    'residences.tab.front': 'সামনের অংশ (ফ্ল্যাট এ এবং বি)',
    'residences.tab.rear': 'পেছনের অংশ (ফ্ল্যাট সি এবং ডি)',
    'residences.specs.title': 'আদর্শ ফ্লোর পরিমাপ',
    'residences.specs.area': 'মোট ফ্লোর এরিয়া',
    'residences.specs.beds': 'বেডরুম',
    'residences.specs.baths': 'বাথরুম',
    'residences.specs.balconies': 'খোলামেলা বারান্দা',
    'residences.specs.lift': 'ডাইরেক্ট কোর লিফট',
    'residences.specs.status': 'বুকিং স্থিতি',
    'residences.specs.status.available': 'বুকিং এর জন্য উন্মুক্ত',
    'residences.specs.status.sold': 'সম্পূর্ণ বুককৃত',
    'residences.specs.price': 'বুকিং মূল্য নির্ধারণ',
    'residences.cta.reserve': 'ফ্ল্যাট বুকিং অনুরোধ',
    'residences.cta.schedule': 'সরাসরি পরিদর্শনের সময়সূচী',

    // FloorPlan Tool interface
    'floorplan.badge': 'ইন্টারেক্টিভ বিআইএম সিমুলেশন',
    'floorplan.title': 'থ্রিডি কাঠামোগত পরিদর্শক',
    'floorplan.subtitle': 'আমাদের ত্রিমাত্রিক ডিজিটাল টুইন এক্সপ্লোর করুন। স্লাব বিচ্ছিন্ন করতে, আলোর দিক পরিবর্তন করতে এবং দেয়ালের দূরত্ব পরিমাপ করতে নিচের নিয়ন্ত্রণ টুল ব্যবহার করুন।',
    'floorplan.ctrl.layer': 'কাঠামোগত স্লাব নির্বাচন',
    'floorplan.ctrl.all': 'সম্পূর্ণ থ্রিডি টাওয়ার',
    'floorplan.ctrl.roof': 'ছাদ বাগান ও সামাজিক এলাকা',
    'floorplan.ctrl.panoramic': 'প্যানোরামিক (তলা ৭-৯)',
    'floorplan.ctrl.executive': 'এক্সিকিউটিভ (তলা ৪-৬)',
    'floorplan.ctrl.ground': 'গ্রাউন্ড লবি এবং পার্কিং স্পেস',
    'floorplan.ctrl.renderMode': 'রেন্ডার মোড পরিবর্তন',
    'floorplan.ctrl.render.solid': 'সলিড কংক্রিট',
    'floorplan.ctrl.render.blue': 'ব্লুপ্রিন্ট গ্লাস',
    'floorplan.ctrl.light': 'আলো এবং সান সিমুলেশন',
    'floorplan.ctrl.light.noon': 'দুপুরের রোদ',
    'floorplan.ctrl.light.morning': 'ভোরের আলো',
    'floorplan.ctrl.light.dusk': 'সন্ধ্যা গোধূলি',
    'floorplan.ctrl.light.midnight': 'মধ্যরাত্রির আভা',
    'floorplan.ctrl.measure': 'দূরত্ব পরিমাপ করুন',
    'floorplan.ctrl.clear': 'পয়েন্ট মুছুন',
    'floorplan.ctrl.elevations': 'আদর্শ এলিভেশন ভিউ',
    'floorplan.ctrl.elev.north': 'উত্তর পাশ',
    'floorplan.ctrl.elev.south': 'দক্ষিণ আইসো',
    'floorplan.ctrl.elev.top': 'ছাদের টপ ভিউ',
    'floorplan.ctrl.orbit': 'ক্যামেরা গতিবিদ্যা',
    'floorplan.ctrl.zoom': 'জুমের গতিবেগ',
    'floorplan.ctrl.pan': 'প্যান করার গতিবেগ',
    'floorplan.ctrl.vr': 'ভিআর গ্লাস মোড পরিবর্তন',
    'floorplan.ctrl.vr.active': 'ভিআর মোড: সক্রিয় আছে',
    'floorplan.ctrl.capture': 'পরিদর্শন স্ন্যাপশট নিন',
    'floorplan.ctrl.capture.title': 'আবরার-২ ফিল্ড ক্যামেরা',
    'floorplan.ctrl.capture.shutter': 'ছবি তুলুন',
    'floorplan.ctrl.capture.toggleSource': 'উৎস পরিবর্তন করুন (ক্যামেরা/থ্রিডি)',
    'floorplan.ctrl.capture.cancel': 'বাতিল করুন',
    'floorplan.ctrl.capture.save': 'জেপিইজি ছবি সংরক্ষণ করুন',
    'floorplan.ctrl.hud.hide': 'টুলবার হাইড করুন',
    'floorplan.ctrl.hud.show': 'টুলবার প্রদর্শন করুন',
    'floorplan.ctrl.tower.isolate': 'ফ্ল্যাট এ/বি সাইড',
    'floorplan.ctrl.tower.composite': 'সম্পূর্ণ টাওয়ার দেখান',
    'floorplan.ctrl.pure': 'সিনেমাটিক ভিউ',

    // BuilderConsole
    'builder.badge': 'বি২বি ডেভেলপার হাব এবং যৌথ উদ্যোগ',
    'builder.title': 'বিল্ডার স্পেক এবং জমি যৌথ উদ্যোগ',
    'builder.subtitle': 'প্রাতিষ্ঠানিক বিনিয়োগকারী, জমির মালিক এবং প্রকৌশলী সংস্থাগুলোর জন্য রাজুক কোড মূল্যায়ন, সাইট বরাদ্দ হিসাব এবং নির্মাণ সামগ্রী পরীক্ষা করার বিশেষ পোর্টাল।',
    'builder.tab.far': 'রাজুক FAR যৌথ ক্যালকুলেটর',
    'builder.tab.specs': 'প্রকৌশল কোয়ালিটি পোর্টাল',
    'builder.tab.cad': 'ডেভেলপার ক্যাড ও টেস্ট প্যাকেজ',
    'builder.calc.parameters': 'যৌথ অংশীদারি অনুপাত হিসাব',
    'builder.calc.parameters.desc': 'রাস্তার প্রশস্ততা এবং কাঠামোগত নকশার ভিত্তিতে জমির মালিকের অংশ হিসাব করতে নিচের স্লাইডারগুলি পরিবর্তন করুন।',
    'builder.calc.plot': 'জমির পরিমাণ',
    'builder.calc.road': 'রাস্তার প্রশস্ততা (ফুট)',
    'builder.calc.mgc': 'সর্বোচ্চ গ্রাউন্ড কভারেজ (MGC)',
    'builder.calc.ownerShare': 'জমির মালিকের অংশ',
    'builder.calc.warning': 'ফার (FAR) এর হিসাবসমূহ সরাসরি রাজুক ঢাকা ইমারত নির্মাণ বিধিমালা ২০০৮ এর ধারা ১৮ এর সাথে সামঞ্জস্যপূর্ণ।',
    'builder.forecasts': 'পৌরসভা উন্নয়ন পূর্বাভাস',
    'builder.forecasts.far': 'রাজুক FAR রেশিও',
    'builder.forecasts.multiplier': 'অনুমোদিত গুণক',
    'builder.forecasts.gross': 'মোট নির্মাণ এলাকা',
    'builder.forecasts.circulation': 'যাতায়াত এরিয়াসহ',
    'builder.forecasts.stories': 'অনুমোদিত তলার সংখ্যা',
    'builder.forecasts.mgccompliant': 'MGC অনুযায়ী উচ্চতা',
    'builder.forecasts.shareDist': 'আনুমানিক অংশীদারি বন্টন (~৯০০ বর্গফুট গড় ইউনিটের ভিত্তিতে)',
    'builder.forecasts.landowner': 'জমির মালিক',
    'builder.forecasts.devshare': 'ডেভেলপার কোম্পানি',
    'builder.forecasts.ownerAppor': 'জমির মালিকের বরাদ্দকৃত অংশ',
    'builder.forecasts.devAppor': 'ডেভেলপার কোম্পানির বরাদ্দকৃত অংশ',
    'builder.forecasts.apartments': 'আদর্শ অ্যাপার্টমেন্টসমূহ',
    'builder.forecasts.shares': 'বাণিজ্যিক অংশীদারিত্ব',
    'builder.forecasts.shareArea': 'মোট শেয়ার এরিয়া',
    'builder.forecasts.note': '*এটি একটি আনুমানিক হিসাব মাত্র। বিশেষ দ্বিপাক্ষিক আলোচনার ভিত্তিতে অংশীদারি স্বত্ব পরিবর্তন হতে পারে।',
    'builder.forecasts.propose': "যৌথ প্রস্তাব প্রেরণ করুন",
    'builder.specs.title': 'প্রকৌশল মানদণ্ড ম্যাট্রিক্স',
    'builder.specs.desc': 'সাধারণ সরকারি মিনিমাম মানের সাথে আবরারের স্বনামধন্য নির্মাণের তুলনামূলক বিবরণ।',
    'builder.specs.qa': 'সার্টিফাইড কোয়ালিটি লগস',
    'builder.specs.sector': 'কাঠামোগত খাত',
    'builder.specs.dhakaMin': 'সাধারণ ঢাকার সর্বনিম্ন মান',
    'builder.specs.abrarExcel': 'আবরার টাওয়ার-২ প্রিমিয়াম মান',
    'builder.specs.margin': 'পৌরসভা মার্জিন উৎকর্ষ',
    'builder.cad.title': 'DXF / PDF ব্লুপ্রিন্ট ডাউনলোড করুন',
    'builder.cad.desc': 'আর্কিটেক্ট, ডেভেলপার ও প্ল্যানাররা অতিসত্বর কাঠামোগত ফ্লোর প্ল্যান, পাইলিং ডেটা লগ এবং রাজুক অনুমোদিত লেআউট ডাউনলোড করতে পারেন।',
    'builder.cad.company': 'কোম্পানি / ডেভেলপার গ্রুপ',
    'builder.cad.email': 'কর্পোরেট ইমেইল ঠিকানা',
    'builder.cad.designation': 'পদবী / প্রতিনিধিত্ব',
    'builder.cad.submit': 'ক্যাড ফাইল জেনারেট করুন',
    'builder.cad.ready': 'প্রস্তুত',
    'builder.cad.dataset': 'বর্তমান ডেটাসেট ইনডেক্স',
    'builder.cad.note': 'অফিসিয়াল ফাইল ডাউনলোডের জন্য কর্পোরেট রেজিস্ট্রেশন আবশ্যক। তাৎক্ষণিক প্রকৌশল জিজ্ঞাসার জন্য সরাসরি মোহাম্মদ আব্দুল মোমেন এর সাথে যোগাযোগ করুন।',

    // Location
    'location.badge': 'ভৌগোলিক অবস্থান এবং যোগাযোগ ব্যবস্থা',
    'location.title': 'দক্ষিণখান আভিজাত্যের কেন্দ্রবিন্দু',
    'location.subtitle': 'উত্তরা ১ নং সেক্টরের সন্নিকটে পূর্ব ফায়দাবাদে অবস্থিত। ঢাকার উত্তরের সর্বোচ্চ ও জলাবদ্ধতা-মুক্ত পরিকল্পিত আবাসিক এলাকা।',
    'location.directions': 'লাইভ যাতায়াত সময় গণনাকারী',
    'location.directions.desc': 'যাতায়াত রুট এবং ঢাকার মূল পয়েন্টগুলো থেকে আবরার টাওয়ারে পৌঁছানোর রুট ম্যাপ ও প্রয়োজনীয় সময় দেখুন।',
    'location.direction.source': 'যাতায়াতের শুরুর স্থান নির্বাচন',
    'location.direction.source.airport': 'হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দর (১.৮ কি.মি.)',
    'location.direction.source.station': 'উত্তরা উত্তর মেট্রো রেল স্টেশন (৩.২ কি.মি.)',
    'location.direction.source.highway': 'ঢাকা-ময়মনসিংহ মহাসড়ক (১.২ কি.মি.)',
    'location.direction.routeInfo': 'যাতায়াত রুট বিশ্লেষণ',
    'location.direction.time': 'আনুমানিক সময়',
    'location.direction.infrastructure': 'রাস্তার ধরন ও অবস্থা',
    'location.direction.landmarks': 'প্রধান ল্যান্ডমার্কসমূহ',
    'location.pin': 'ভৌগোলিক মানচিত্রের সুনির্দিষ্ট বিন্দু',

    // Contact form panel
    'contact.badge': 'বুকিং এবং ফ্ল্যাট বরাদ্দ বিবরণ বিবরণ',
    'contact.title': 'আপনার প্রিমিয়াম ফ্ল্যাটটি বুক করুন',
    'contact.subtitle': 'আমাদের বোর্ড সরাসরি এসক্রো-নিরাপদ পেমেন্ট গ্রহণ করে। বিস্তারিত আলোচনার জন্য আপনার কর্পোরেট তথ্য বা সরাসরি পরিদর্শনের সূচী বুক করুন।',
    'contact.form.title': 'কাঠামোগত বুকিং ও এসক্রো অনুরোধ ফর্ম',
    'contact.form.name': 'আপনার পুরো নাম / কোম্পানির নাম',
    'contact.form.email': 'কর্পোরেট ইমেইল ঠিকানা',
    'contact.form.phone': 'মোবাইল নম্বর / যোগাযোগের ঠিকানা',
    'contact.form.flat': 'পছন্দের ফ্লোর এবং ফ্ল্যাট ইউনিট নম্বর',
    'contact.form.flat.select': 'পছন্দের ফ্ল্যাট গ্রিড নির্বাচন করুন',
    'contact.form.flat.opt': 'গ্রিড ইউনিট',
    'contact.form.flat.suite': 'স্পেশাল ডুপ্লেক্স স্যুট (মূল্য আলোচনা সাপেক্ষ)',
    'contact.form.intent': 'যোগাযোগের প্রধান উদ্দেশ্য',
    'contact.form.intent.select': 'বুকিং পর্যায় নির্বাচন করুন',
    'contact.form.intent.investor': 'যৌথ অংশীদারি প্রস্তাব (জমির মালিক / ইনভেস্টর)',
    'contact.form.intent.buyer': 'ব্যক্তিগত কর্নার ফ্ল্যাট বুকিং',
    'contact.form.intent.architect': 'ব্লুপ্রিন্ট ও সয়েল টেস্ট লগ নিরীক্ষা',
    'contact.form.notes': 'অতিরিক্ত কোনো মন্তব্য বা বিশেষ অনুরোধ',
    'contact.form.submit': 'নিরাপদ বুকিং তথ্য প্রেরণ করুন',
    'contact.form.security': 'নিরাপদ ISO-27001 TLS এনক্রিপশন সক্রিয়',
    'contact.escrow': 'যাচাইকৃত কর্পোরেট এসক্রো বিবরণ',
    'contact.escrow.desc': 'আসন বুকিং বা যৌথ আলোচনার অগ্রিম কিস্তি আমাদের অনুমোদিত ব্যাংক চ্যানেলের মাধ্যমে নিরাপদে জমা দিতে পারেন।',
    'contact.escrow.beneficiary': 'হিসাব নাম (Beneficiary)',
    'contact.escrow.institution': 'ব্যাংক ও শাখা (Institution)',
    'contact.escrow.routing': 'রাউটিং নম্বর ও সুইফ্ট কোড',
    'contact.escrow.address': 'অফিসিয়াল কর্পোরেট কার্যালয়',

    // Chatbot
    'chatbot.title': 'আবরার-২ কৃত্তিম বুদ্ধিমত্তা সহকারী',
    'chatbot.status': 'বি২বি এআই এডভাইজার সচল আছে',
    'chatbot.placeholder': 'FAR নিয়ম, বিএসআরএম গ্রেড ইত্যাদি সম্পর্কে জিজ্ঞাসা করুন...',
    'chatbot.suggest.far': '১০ কাঠা জমির জন্য রাজুক FAR রেশিও কত?',
    'chatbot.suggest.seismic': 'ভবনটিতে কি কি সিসমিক ডিজাইন ব্যবহৃত হয়েছে?',
    'chatbot.suggest.materials': 'কনক্রিট ও স্টিল রডের গ্রেড সম্পর্কে বলুন।'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('abrar_lang');
    return (saved === 'bn' ? 'bn' : 'en') as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('abrar_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
